---
- name: Install common packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  tags:
    - instpack
- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true
  tags:
    - dockerkey
- name: Add Docker apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
    update_cache: yes
  tags:
    - addrepo
- name: Install Docker apt package
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify:
    - restart_docker
  tags:
    - instdocker
- name: Install Docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
    dest: /usr/local/bin/docker-compose
    mode: +x
  tags:
    - instcompose
