plugin: aws_ec2
#regions:
#  - us-east-2
keyed_groups:
  # add hosts to tag_Name_value groups for each aws_ec2 host's tags.Name variable
  - key: tags.Name
    prefix: tag_Name_
    separator: ""
groups:
  # add hosts to the group test if any of the dictionary's keys or values is the word 'Test'
  test: "'Test' in (tags|list)" 
