---
- name: Customize WordPress
  hosts: tag_Name_Work_Host
  become: yes

  tasks:
    - name: Disable Wizard
      shell: |
        docker-compose exec wordpress wp core install --url=wpspa.tk --title="SPA Title" --admin_name=admin --admin_password=admin123 --admin_email=dk.khomich@spagomel.by
        docker-compose exec wordpress wp plugin list
      args:
        chdir: /applic
        executable: /bin/bash
      register: value
      tags:
        - diswiz  
    - debug:
        msg: "{{ value.stdout }}"
