---
- hosts: tag_Name_Blue_Host
  become: yes
  tasks:
    - name: Update Blue
      shell: |
        docker-compose exec wordpress wp core install --url=wp-blue.tk --title="VERSION NUMBER 2" --admin_name=admin --admin_password=admin123 --admin_email=dk.khomich@spagomel.by
        docker-compose exec wordpress wp theme install apex-business
        docker-compose exec wordpress wp theme activate apex-business
      args:
        chdir: /applic
        executable: /bin/bash

- hosts: tag_Name_Green_Host
  become: yes  
  tasks:
    - name: Update Green
      shell: |
        docker-compose exec wordpress wp core install --url=wp-green.tk --title="VERSION NUMBER 1" --admin_name=admin --admin_password=admin123 --admin_email=dk.khomich@spagomel.by
        docker-compose exec wordpress wp theme install business-street
        docker-compose exec wordpress wp theme activate business-street
      args:
        chdir: /applic
        executable: /bin/bash
