---
- name: Customize WordPress
  hosts: tag_Name_Blue_Host
  become: yes

  tasks:
    - name: Disable Wizard
      shell: |
        docker-compose exec wordpress wp core install --url=wpspa.tk --title="VERSION NUMBER 2" --admin_name=admin --admin_password=admin123 --admin_email=dk.khomich@spagomel.by
        docker-compose exec wordpress wp theme install apex-business
        docker-compose exec wordpress wp theme activate apex-business
      args:
        chdir: /applic
        executable: /bin/bash
